#!/usr/bin/env bash
# shellcheck shell=bash
# HA clone + sync of current portal

ask_ha_site() {
  banner "Параметры резервного клона (HA)"
  prompt YP_SITE_DOMAIN "Домен резерва (может совпадать с primary или быть standby.young…)" "standby.young.idivles.ru"
  prompt YP_PRIMARY_HOST "Primary host (текущий сайт)" "young.idivles.ru"
  prompt YP_PRIMARY_SSH_HOST "SSH host primary (для pull с primary)" "176.124.204.53"
  prompt YP_PRIMARY_SSH_PORT "SSH порт primary" "4488"
  prompt YP_PRIMARY_SSH_USER "SSH user primary" "root"
  prompt YP_PRIMARY_DIR "Каталог портала на primary" "/opt/sochi-portal"
  echo "Доступ к primary для синка:"
  echo "  1) пароль  2) ключ"
  read -r -p "Способ [1/2]: " pa
  if [[ "$pa" == "2" ]]; then
    prompt YP_PRIMARY_SSH_KEY "Ключ к primary" "$HOME/.ssh/id_ed25519"
    YP_PRIMARY_SSH_PASS=""
  else
    prompt_secret YP_PRIMARY_SSH_PASS "Пароль SSH primary"
    YP_PRIMARY_SSH_KEY=""
  fi
  prompt YP_INSTALL_DIR "Каталог на standby VPS" "/opt/sochi-portal"
  prompt YP_ROLE "Роль этого узла: standby|primary" "standby"
  prompt YP_SYNC_INTERVAL_MIN "Интервал синка (мин)" "15"
  prompt YP_SYNC_UPLOADS "Синкать uploads? (y/n)" "y"
  prompt YP_FAILOVER_MODE "Failover: manual|dns-ttl|floating-ip" "manual"
  prompt YP_REPLICA_SHARED_SECRET "Общий секрет репликации (или Enter=сгенерировать)" ""
  if [[ -z "${YP_REPLICA_SHARED_SECRET}" ]]; then
    YP_REPLICA_SHARED_SECRET="$(random_secret)"
  fi
  YP_NEXTAUTH_SECRET="${YP_NEXTAUTH_SECRET:-}"  # will copy from primary .env if empty
  export YP_SITE_DOMAIN YP_PRIMARY_HOST YP_PRIMARY_SSH_HOST YP_PRIMARY_SSH_PORT YP_PRIMARY_SSH_USER
  export YP_PRIMARY_DIR YP_PRIMARY_SSH_KEY YP_PRIMARY_SSH_PASS YP_INSTALL_DIR YP_ROLE
  export YP_SYNC_INTERVAL_MIN YP_SYNC_UPLOADS YP_FAILOVER_MODE YP_REPLICA_SHARED_SECRET YP_NEXTAUTH_SECRET
}

run_ha_clone() {
  banner "HA clone install"
  require_cmd rsync

  info "Готовлю standby VPS (Docker/nginx)…"
  remote_bash <<'EOS'
set -euo pipefail
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq curl ca-certificates rsync nginx jq openssl postgresql-client fail2ban ufw
command -v docker >/dev/null || curl -fsSL https://get.docker.com | sh
systemctl enable --now docker
EOS

  info "Копирую код с primary → standby…"
  # Pull from primary onto local tmp, then push to standby — or remote-to-remote via standby
  remote "mkdir -p '$YP_INSTALL_DIR' /opt/yp-ha /var/lib/yp-ha /var/log/yp-ha"

  # Install sync scripts onto standby
  scp_to "$ROOT_DIR/bin/yp-ha-sync" /opt/yp-ha/yp-ha-sync
  scp_to "$ROOT_DIR/bin/yp-ha-promote" /opt/yp-ha/yp-ha-promote
  scp_to "$ROOT_DIR/bin/yp-ha-health" /opt/yp-ha/yp-ha-health
  scp_to "$ROOT_DIR/systemd/yp-ha-sync.service" /etc/systemd/system/yp-ha-sync.service
  scp_to "$ROOT_DIR/systemd/yp-ha-sync.timer" /etc/systemd/system/yp-ha-sync.timer
  scp_to "$ROOT_DIR/systemd/yp-ha-watchdog.service" /etc/systemd/system/yp-ha-watchdog.service
  scp_to "$ROOT_DIR/systemd/yp-ha-watchdog.timer" /etc/systemd/system/yp-ha-watchdog.timer

  # Write HA config on standby
  # shellcheck disable=SC2087
  remote_bash <<EOS
set -euo pipefail
cat > /etc/yp-ha.conf <<CONF
# Generated by yp-provision
YP_ROLE=$YP_ROLE
YP_SITE_DOMAIN=$YP_SITE_DOMAIN
YP_PRIMARY_HOST=$YP_PRIMARY_HOST
YP_PRIMARY_SSH_HOST=$YP_PRIMARY_SSH_HOST
YP_PRIMARY_SSH_PORT=$YP_PRIMARY_SSH_PORT
YP_PRIMARY_SSH_USER=$YP_PRIMARY_SSH_USER
YP_PRIMARY_DIR=$YP_PRIMARY_DIR
YP_INSTALL_DIR=$YP_INSTALL_DIR
YP_SYNC_UPLOADS=$YP_SYNC_UPLOADS
YP_FAILOVER_MODE=$YP_FAILOVER_MODE
YP_REPLICA_SHARED_SECRET=$YP_REPLICA_SHARED_SECRET
YP_HEALTH_URL=https://$YP_PRIMARY_HOST/api/health
YP_LOCAL_HEALTH_URL=http://127.0.0.1:3000/api/health
STATE_DIR=/var/lib/yp-ha
LOG=/var/log/yp-ha/ha.log
CONF
chmod 600 /etc/yp-ha.conf

# Store primary SSH auth for sync (prefer key file uploaded separately)
if [[ -n '${YP_PRIMARY_SSH_KEY}' && -f '${YP_PRIMARY_SSH_KEY}' ]]; then
  echo "Upload primary key manually to /root/.ssh/yp-primary and set YP_PRIMARY_SSH_KEY in conf" >&2
fi
if [[ -n '${YP_PRIMARY_SSH_PASS}' ]]; then
  echo '${YP_PRIMARY_SSH_PASS}' > /etc/yp-ha.pass
  chmod 600 /etc/yp-ha.pass
  echo 'YP_PRIMARY_SSH_PASS_FILE=/etc/yp-ha.pass' >> /etc/yp-ha.conf
fi

chmod +x /opt/yp-ha/yp-ha-sync /opt/yp-ha/yp-ha-promote /opt/yp-ha/yp-ha-health
systemctl daemon-reload
# Adjust timer interval
sed -i 's/OnUnitActiveSec=.*/OnUnitActiveSec=${YP_SYNC_INTERVAL_MIN}min/' /etc/systemd/system/yp-ha-sync.timer
systemctl enable --now yp-ha-sync.timer
systemctl enable --now yp-ha-watchdog.timer

# First sync (may take long)
/opt/yp-ha/yp-ha-sync || echo "WARN: первый sync завершился с ошибкой — проверьте conf" >&2

# nginx reverse proxy like primary
cat > /etc/nginx/sites-available/sochi-portal.conf <<NGX
server {
  listen 80;
  server_name $YP_SITE_DOMAIN $YP_PRIMARY_HOST;
  client_max_body_size 50m;
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_http_version 1.1;
    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Upgrade \$http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
NGX
ln -sfn /etc/nginx/sites-available/sochi-portal.conf /etc/nginx/sites-enabled/sochi-portal.conf
nginx -t && systemctl reload nginx
EOS

  ok "HA standby подготовлен"
  cat <<EOF

Дальше:
  1) На primary положите /etc/yp-ha-primary.conf и включите экспорт бэкапов (см. docs).
  2) В админке → Система → Репликация укажите peer и секрет:
       $YP_REPLICA_SHARED_SECRET
  3) DNS: либо короткий TTL на A-запись, либо отдельный standby-домен + ручной promote.
  4) Тест: остановите primary web → promote standby → проверьте /api/health.

EOF
}
